require("user.options")
require("user.keymaps")
require("user.plugins")
require("user.treesitter")
require("user.telescope")
require("user.autopairs")
require("user.nvim-tree")
require("user.bufferline") -- this one throws the unknown plugin error on startup
require("user.lualine")
require("user.indentline")
